export enum Province {
    TUYEN_QUANG = 'tuyen_quang',
    LAO_CAI = 'lao_cai',
    THAI_NGUYEN = 'thai_nguyen',
    PHU_THO = 'phu_tho',
    BAC_NINH = 'bac_ninh',
    HUNG_YEN = 'hung_yen',
    HAI_PHONG = 'hai_phong',
    NINH_BINH = 'ninh_binh',
    QUANG_TRI = 'quang_tri',
    DA_NANG = 'da_nang',
    QUANG_NGAI = 'quang_ngai',
    GIA_LAI = 'gia_lai',
    KHANH_HOA = 'khanh_hoa',
    LAM_DONG = 'lam_dong',
    DAK_LAK = 'dak_lak',
    HO_CHI_MINH = 'ho_chi_minh',
    DONG_NAI = 'dong_nai',
    TAY_NINH = 'tay_ninh',
    CAN_THO = 'can_tho',
    VINH_LONG = 'vinh_long',
    DONG_THAP = 'dong_thap',
    CA_MAU = 'ca_mau',
    AN_GIANG = 'an_giang',
    HA_NOI = 'ha_noi',
    HUE = 'hue',
    LAI_CHAU = 'lai_chau',
    DIEN_BIEN = 'dien_bien',
    SON_LA = 'son_la',
    LANG_SON = 'lang_son',
    QUANG_NINH = 'quang_ninh',
    THANH_HOA = 'thanh_hoa',
    NGHE_AN = 'nghe_an',
    HA_TINH = 'ha_tinh',
    CAO_BANG = 'cao_bang',
}


export const PROVINCE_LABEL: Record<Province, string> = {
    [Province.TUYEN_QUANG]: 'Tỉnh Tuyên Quang',
    [Province.LAO_CAI]: 'Tỉnh Lào Cai',
    [Province.THAI_NGUYEN]: 'Tỉnh Thái Nguyên',
    [Province.PHU_THO]: 'Tỉnh Phú Thọ',
    [Province.BAC_NINH]: 'Tỉnh Bắc Ninh',
    [Province.HUNG_YEN]: 'Tỉnh Hưng Yên',
    [Province.HAI_PHONG]: 'Thành phố Hải Phòng',
    [Province.NINH_BINH]: 'Tỉnh Ninh Bình',
    [Province.QUANG_TRI]: 'Tỉnh Quảng Trị',
    [Province.DA_NANG]: 'Thành phố Đà Nẵng',
    [Province.QUANG_NGAI]: 'Tỉnh Quảng Ngãi',
    [Province.GIA_LAI]: 'Tỉnh Gia Lai',
    [Province.KHANH_HOA]: 'Tỉnh Khánh Hòa',
    [Province.LAM_DONG]: 'Tỉnh Lâm Đồng',
    [Province.DAK_LAK]: 'Tỉnh Đắk Lắk',
    [Province.HO_CHI_MINH]: 'Thành phố Hồ Chí Minh',
    [Province.DONG_NAI]: 'Tỉnh Đồng Nai',
    [Province.TAY_NINH]: 'Tỉnh Tây Ninh',
    [Province.CAN_THO]: 'Thành phố Cần Thơ',
    [Province.VINH_LONG]: 'Tỉnh Vĩnh Long',
    [Province.DONG_THAP]: 'Tỉnh Đồng Tháp',
    [Province.CA_MAU]: 'Tỉnh Cà Mau',
    [Province.AN_GIANG]: 'Tỉnh An Giang',
    [Province.HA_NOI]: 'Thành phố Hà Nội',
    [Province.HUE]: 'Thành phố Huế',
    [Province.LAI_CHAU]: 'Tỉnh Lai Châu',
    [Province.DIEN_BIEN]: 'Tỉnh Điện Biên',
    [Province.SON_LA]: 'Tỉnh Sơn La',
    [Province.LANG_SON]: 'Tỉnh Lạng Sơn',
    [Province.QUANG_NINH]: 'Tỉnh Quảng Ninh',
    [Province.THANH_HOA]: 'Tỉnh Thanh Hóa',
    [Province.NGHE_AN]: 'Tỉnh Nghệ An',
    [Province.HA_TINH]: 'Tỉnh Hà Tĩnh',
    [Province.CAO_BANG]: 'Tỉnh Cao Bằng',
};
